homeassistant:
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: !secret home_timezone
  name: Hubs
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 172.20.0.0/16
        - 10.0.12.0/24
        - 10.0.11.174/32
      allow_bypass_login: true
    - type: homeassistant

# view_event: !include view_event.yaml

http:
  base_url: https://hubs.automation.home.prettybaked.com
  
frontend:

config:

isy994: !include isy994.yaml
hue:
  bridges: !include_dir_list hue_bridges
remote: !include_dir_list remotes
light: !include_dir_list lights


mqtt: !include mqtt.yaml
mqtteventstream: !include eventstream.yaml
