homeassistant:
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: !secret home_timezone
  name: Hub

http:

frontend:

# zwave: !include zwave.yaml
# zha: !include zigbee.yaml
isy994: !include isy994.yaml
